### ISSUE TITLE
chatroom example: cannot set nick and send message(0.1.33)

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#104]
After setup Nick in Nick's input and then clicking Message'input, 
We have the following error message
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-examples/lib/python3.11/site-packages/pynecone/state.py", line 693, in _process_event
    events = await fn(**payload)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/chatroom/chatroom/chatroom.py", line 33, in nick_change
    await broadcast_nicks()
  File "/Users/milochen/git/py-webapp/chatroom/chatroom/chatroom.py", line 117, in broadcast_nicks
    await broadcast_event("state.set_nicks", payload=dict(nicks=nicks))
  File "/Users/milochen/git/py-webapp/chatroom/chatroom/chatroom.py", line 94, in broadcast_event
    update = await state._process(
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: object async_generator can't be used in 'await' expression
```

```
My Testing Environment
        OS Darwin 22.4.0
        Pynecone 0.1.33
        Python 3.11.3
        Node v16.8.0
        Bun 0.5.9
```

**Comment by masenf** [comment]
fixed in #124

**Comment by milochen0418** [comment]
Nice :D 
Solved by 
- https://github.com/pynecone-io/pynecone-examples/pull/124
