### ISSUE TITLE
stable_diffusion example: Mac cpu-only failed when click Generate New Image (0.1.33)

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#116]
```
Fetching 13 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [21:08<00:00, 97.55s/it]
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: ███████████████████████████████▏                                                                        | 1.45G/3.46G [10:20<12:54, 2.60MB/s]
```nloading (…)ch_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.46G/3.46G [21:06<00:00, 4.58MB/s]
pip install accelerate

.
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pc0133/lib/python3.11/site-packages/pynecone/state.py", line 697, in _process_event
    events = fn(**payload)
             ^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/stable_diffusion/stable_diffusion/stable_diffusion.py", line 64, in stable_diffusion
    sd_image = img2img(
               ^^^^^^^^
  File "/Users/milochen/git/py-webapp/stable_diffusion/stable_diffusion/img2img_mac.py", line 41, in img2img
    pipe = pipe.to("mps")
           ^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pc0133/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 682, in to
    module.to(torch_device, torch_dtype)
  File "/Users/milochen/anaconda3/envs/pc0133/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pc0133/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/milochen/anaconda3/envs/pc0133/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pc0133/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`
```

```
My Testing Environment
        OS Darwin 22.4.0
        Pynecone 0.1.34a0
        Python 3.11.3
        Node v16.8.0
        Bun 0.5.9
```
My MacBook Pro is using Intel CPU.
More information of my MacBook is here
<img width="262" alt="Screenshot 2023-06-19 at 1 27 25 AM" src="https://github.com/pynecone-io/pynecone-examples/assets/12568287/abea8de3-2244-4ecd-90d7-c39cf9a4cbff">

**Comment by milochen0418** [comment]
Some question related to this issue
https://stackoverflow.com/questions/72313510/runtimeerror-the-mps-backend-is-supported-on-macos-12-3-current-os-version-can

**Comment by milochen0418** [comment]
More reference 
https://github.com/oobabooga/text-generation-webui/issues/1337

**Comment by milochen0418** [comment]
After click Generate New Image, it will use `img2img_mac.py` 
Right now, the current code only support `mps` 

Apple Metal Performance Shaders (MPS)
The MPS backend extends the PyTorch framework by providing scripts and capabilities to set up and run operations on Mac. MPS optimizes compute performance with kernels that are fine-tuned for the unique characteristics of each Metal GPU family.

**Comment by milochen0418** [comment]
> Hi @milochen0418 great this is a great point. I am just about to submit a PR that will also allow you to run this with only a CPU on a mac. It will take about 4/5 minutes per image if running on a cpu only and running for 30 inference steps.
> 
> To speed this up further you can make the image smaller, by changing the width parameter in image_style inside of styles.py, or you can reduce the number of inference steps further. Hope this helps.

Hi @tgberkeley,  
You are so nice. 
It's wonderful to have your code. Let everyone enjoy the stable diffusion of pynecone app. 
It works on my old Mac with CPU only from this PR
- https://github.com/pynecone-io/pynecone-examples/pull/117

And the following is my testing result
- https://github.com/pynecone-io/pynecone-examples/pull/117#pullrequestreview-1496297117

**Comment by milochen0418** [comment]
Bug solved by 
- https://github.com/pynecone-io/pynecone-examples/pull/117
