### ISSUE TITLE
twitter is not working well after pynecone 0.1.24 -> 0.1.27 

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#60]
The twitter example is working well in the following condition.
```
pynecone==0.1.24
bun==5.9
node==20.0.0
```

After using 0.1.27 
```
pynecone==0.1.27
bun==5.9
node==20.0.0
```
When we  type in the search field, 
We have the following error from the log. 
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-examples/lib/python3.11/site-packages/pynecone/state.py", line 655, in _process_event
    events = fn(**payload)
             ^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/twitter/twitter/home.py", line 51, in set_search
    return self.get_tweets()
           ^^^^^^^^^^^^^^^^^
TypeError: HomeState.get_tweets() missing 1 required positional argument: 'self'
```

And the page is like 
<img width="952" alt="Screenshot 2023-04-30 at 6 20 03 PM" src="https://user-images.githubusercontent.com/12568287/235347951-41d53db8-1448-4ba6-8106-847e964aa8a4.png">

If you click Tweet button, it also has the bug too.
And it debug message is the following
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-examples/lib/python3.11/site-packages/pynecone/state.py", line 655, in _process_event
    events = fn(**payload)
             ^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/twitter/twitter/home.py", line 20, in toggle_tweet
    return self.get_tweets()
           ^^^^^^^^^^^^^^^^^
TypeError: HomeState.get_tweets() missing 1 required positional argument: 'self'
```

**Comment by milochen0418** [comment]
Solve this issue by the following commit 
https://github.com/pynecone-io/pynecone-examples/pull/59/commits/3629ab46d7def2ea9be98f3cf07ae83e01ef25e4
