### ISSUE TITLE
Get warning log and miss running progress bar in sales example with pynecone==0.1.28

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone-examples#61]
Get warning log in sales example with pynecone==0.1.28
Warning message and find out the frontend appears to miss the light. it doesn't have some moving light in new version after 0.1.24.
The light is from the following code. It is between the heading text and textarea.
```
      pc.cond(
          State.gen_response,
          pc.progress(is_indeterminate=True, color="blue", width="100%"),
          pc.progress(value=0, width="100%"),
      ),
```
And the warning message is the following
```
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at textarea
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/textarea/dist/chakra-ui-textarea.cjs.dev.js:70:23
    at div
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.cjs.dev.js:910:24
    at VStack
    at div
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.cjs.dev.js:910:24
    at VStack
    at div
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Component (webpack-internal:///./pages/index.js:38:88)
    at EnvironmentProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.cjs.dev.js:120:24)
    at ColorModeProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.cjs.dev.js:228:21)
    at ThemeProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:106:21)
    at ThemeProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js:57:27)
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at ChakraProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/provider/dist/chakra-ui-provider.cjs.dev.js:40:24)
    at MyApp (webpack-internal:///./pages/_app.js:23:18)
    at StyleRegistry (/Users/milochen/git/py-webapp/sales/.web/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/Users/milochen/git/py-webapp/sales/.web/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/milochen/git/py-webapp/sales/.web/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/Users/milochen/git/py-webapp/sales/.web/node_modules/next/dist/server/render.js:614:21)
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at textarea
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/textarea/dist/chakra-ui-textarea.cjs.dev.js:70:23
    at div
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.cjs.dev.js:910:24
    at VStack
    at div
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/layout/dist/chakra-ui-layout.cjs.dev.js:910:24
    at VStack
    at div
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Component (webpack-internal:///./pages/index.js:38:88)
    at EnvironmentProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.cjs.dev.js:120:24)
    at ColorModeProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.cjs.dev.js:228:21)
    at ThemeProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:106:21)
    at ThemeProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js:57:27)
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at /Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at ChakraProvider (/Users/milochen/git/py-webapp/sales/.web/node_modules/@chakra-ui/provider/dist/chakra-ui-provider.cjs.dev.js:40:24)
    at MyApp (webpack-internal:///./pages/_app.js:23:18)
    at StyleRegistry (/Users/milochen/git/py-webapp/sales/.web/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/Users/milochen/git/py-webapp/sales/.web/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/milochen/git/py-webapp/sales/.web/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/Users/milochen/git/py-webapp/sales/.web/node_modules/next/dist/server/render.js:614:21)
```
The following picture is the working GUI but not work on its center line. 
<img width="1429" alt="Screenshot 2023-05-02 at 2 36 37 PM" src="https://user-images.githubusercontent.com/12568287/235596608-f3dd52d5-022d-4d0c-8ab8-314d23337e46.png">

**Comment by milochen0418** [comment]
- The warning message is because of some text field don't  put value + on_change together. 
- progressing bar is another issue 
Thus , there are two issues.
